"""empty message

Revision ID: 0b94bee72ca0
Revises: 7f381a973555
Create Date: 2022-01-28 22:32:49.941121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b94bee72ca0'
down_revision = '7f381a973555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', sa.String(), nullable=False))
    op.add_column('user', sa.Column('_is_active', sa.Boolean(), nullable=False))
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', '_is_active')
    op.drop_column('user', '_password')
    # ### end Alembic commands ###
